### ISSUE TITLE
Content fails to load with setup described

### ISSUE THREAD

**Issue by mituller** [adi518/vue-breakpoint-component#17]
I'm sure this is simple as others seem to have this working. I have an app started with Vue CLI 3, and am following the instructions. I have installed the module with `npm install --save vue-breakpoint-component` and the added `import { VShowAt } from 'vue-breakpoint-component'`

Finally I registered the component with VShowAt

When I have all that in place, the page loads with a blank page. If I remove it, the page loads as expected. Something isn't right here, but I don't know what it could be. Everything seems right and I don't get info back from the console that gives me any guidance.

**Comment by adi518** [comment]
Hi, I need to do some updating on this component. I suspect some stuff breaks on newer versions of Vue.

**Comment by AndrewGorman** [comment]
Hey @adi518 , firstly thanks for making this! Seems like it could be a super useful tool, but alas, I'm having the same issues as @mituller, except the console is complaining about `regeneratorRuntime` not being defined. I don't have a lot of free time but if you don't have time to dig into this issue I may be able to find some time to help out if you accept PRs

**Comment by adi518** [comment]
See [this](https://github.com/adi518/vue-facebook-login-component/issues/17).

**Comment by intositeme** [comment]
Having the same issue. 
Imported `regeneratorRuntime` fixed the error
