### ISSUE TITLE
Custom Config does not work.

### ISSUE THREAD

**Issue by intositeme** [adi518/vue-breakpoint-component#20]
Followed the docs and tried to use the `Model` but my component model is just an empty object.

**Comment by igrslv** [comment]
I can report the same issue without any console errors or warnings.

**Comment by adi518** [comment]
OK, I'll look into it, thanks.

**Comment by adi518** [comment]
You are saying custom config doesn't work, but specify empty model in your description. So I need more context. Did you define custom configuration and getting an empty model or simply getting an empty model?

**Comment by adi518** [comment]
OK, made some progress. There was a nasty little bug in configuration merge. However, it didn't affect the model, I was still getting readouts just fine. Hold short for a patch release to fix custom configuration.

**Comment by adi518** [comment]
Custom config should now be fixed with [1.2.3](https://github.com/adi518/vue-breakpoint-component/releases/tag/v1.2.3).
