### ISSUE TITLE
v-hide/show-at broken ?

### ISSUE THREAD

**Issue by Titoine** [adi518/vue-breakpoint-component#21]
Hi,
as you can see here:  
https://codesandbox.io/s/validation-components-bootstrapvue-bml0e?fontsize=14&hidenavigation=1&theme=dark
The v-show-at and v-hide-at component seems to be broken.
Maybe I'm doing something wrong ? Anyways the v-breakpoint works well.

**Comment by adi518** [comment]
Done some fixes lately so this looks like a regression. I'll fix it in a day or two, thanks.

**Comment by adi518** [comment]
Should be fixed now with the release of `1.2.6`.
