### ISSUE TITLE
IE11 support?

### ISSUE THREAD

**Issue by LordOfCorners** [adi518/vue-breakpoint-component#5]
Hi. Thanks for the wonderful work on this. I was confused by this: 

> This component relies on matchMedia API (IE 10+). For older browsers and IE, you will need a polyfill.

Does it support IE11? The first sentence seems like it does, and the second one seems like it doesn't. I am trying to use it in IE11 and get an error that says 

>Object doesn't support property or method 'entries'

Do you have any advice?

**Comment by adi518** [comment]
I'll update the wording to prevent confusion. Any IE below 10 doesn't support the `matchMedia` API so "older browsers and IE" refers to IE <= 9. As for `Object doesn't support property or method 'entries'`. IE doesn't support the Object class static method `entries`, which transforms an object to array. MDN has a compatibility table [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/entries) (and for every other language API so use it a lot to determine whether a given API works with old browsers). To mitigate this issue you have to include `babel-polyfill`, which will make `Object.entries` available to IE <= 11. The demo site for this component is compatible with IE 11, so you can just follow along from [here](https://github.com/adi518/vue-breakpoint-component/blob/master/docs/src/main.js). It's fairly simple, add `babel-polyfill` to your project dependencies and in your `main.js` add:

```js
import 'babel-polyfill'

// ...rest of your code
```

**Comment by adi518** [comment]
You can't solve it like that. Also, the component is already transpiled to ES5, however Babel doesn't transpile `Object.entries` and few other APIs.

If you want to avoid include a large polyfill, you can try this instead:

```js
require('core-js/fn/object/entries')
```

**Comment by LordOfCorners** [comment]
Thanks!! Works perfectly. Really appreciate your help.
