### ISSUE TITLE
Question about usage

### ISSUE THREAD

**Issue by gerasimvol** [adi518/vue-breakpoint-component#6]
Usually we need breakpoints through all app (in all components and places), so should I wrap whole site in your component?🤔
Can you give real life example of usage? Or just wrap separate html where I need media queries?

**Comment by adi518** [comment]
Did you go through the docs? you define the breakpoints once for all `<v-breakpoint>` instances using the `Ctor` class. See example below (it also appears in the docs).

Then, you can compose it everywhere you need to access the state. It's also optimized so the detection itself is a singleton, no matter how many instances of `<v-breakpoint>` exist.

To be able to use it in a way where you wrap `<App>`, I have to implement provide/inject, so you right now you can't use it like that. However, I will consider adding this feature in the next version.

This how you configure the component with your own breakpoints:

```js
import Vue from 'vue'
import { Ctor } from 'vue-breakpoint-component'

export { Model } from 'vue-breakpoint-component'

const config = {
  debounceTime: 50,
  experimental: false,
  breakpoints: {
    small: '(min-width: 576px)',
    medium: '(min-width: 768px)',
    large: '(min-width: 992px)',
    xlarge: '(min-width: 1200px)'
    ...
  }
}

const components = { ...new Ctor(Vue, config) }

export const VShowAt = components.VShowAt
export const VHideAt = components.VHideAt
export const VBreakpoint = components.VBreakpoint

export default VBreakpoint
```
