### ISSUE TITLE
Documentation on custom configuration is incorrect

### ISSUE THREAD

**Issue by Sun0fABeach** [adi518/vue-breakpoint-component#7]
In section "Configuration", please change

`const { VShowAt, VHideAt, VBreakpoint } = new Ctor({ experimental: true })`

to 

`const { VShowAt, VHideAt, VBreakpoint } = new Ctor(Vue, config)`

**Comment by adi518** [comment]
My bad, the readme on GitHub doesn't represent the published readme (version 1.1.1). Use [this](https://adi518.github.io/vue-breakpoint-component/#/) as the source of truth while I fix this, thanks.

**Comment by adi518** [comment]
Should be fixed now along with new release `1.2.1` (docs are also updated).
