### ISSUE TITLE
Breakpoint model constructor returns empty object

### ISSUE THREAD

**Issue by Sun0fABeach** [adi518/vue-breakpoint-component#8]
```
import { Model  } from 'vue-breakpoint-component'
console.log(new Model())
```

The log shows me an empty object. Also, using it as a model with `<v-breakpoint>` doesn't have any effect on it. It stays empty and I can't query breakpoints.

My code in context:

**Template**
```
<VBreakpoint v-model="breakpoint" />
<div v-if="breakpoint.isLarge />
```

**Script**
```
import { Model as VBreakPointModel, VBreakpoint } from 'vue-breakpoint-component'
...
components: {
  VBreakpoint
},
data () {
  return {
    breakpoint: new VBreakPointModel(),
  }
},
```

The div will _never_ be visible.

**Comment by adi518** [comment]
Does it change in [devtools](https://chrome.google.com/webstore/detail/vuejs-devtools/nhdogjmejiglipccpnnnanhbledajbpd?hl=en)?

**Comment by Sun0fABeach** [comment]
It doesn't.

![vue-breakpoint-model](https://user-images.githubusercontent.com/8113158/54476446-e1acb180-47fd-11e9-8609-ebdea42fc608.png)

**Comment by adi518** [comment]
How did you consume it? did you add it to your project from npm?

**Comment by Sun0fABeach** [comment]
Yes, I use npm.

**Comment by adi518** [comment]
Which version? `1.1.1`? I setup a repro with Vue CLI 3.x and component version `1.1.1`, and everything works. Did you resize the browser?

**Comment by Sun0fABeach** [comment]
Yes, I resized the browser.

I tried reproducing the error in a new empty Vue CLI 3 project and got stuck on another problem.
Simply doing this import:

`import { VBreakpoint } from 'vue-breakpoint-component'`

will produce this error in the browser:

`Uncaught ReferenceError: regeneratorRuntime is not defined`

I'm on version 1.2.1 now. I created the project using Vue CLI v3.5.1.

**Comment by adi518** [comment]
That one is an easy fix, just add `babel-polyfill` to your dependencies and import it like so: https://github.com/adi518/vue-breakpoint-component/blob/master/docs/src/main.js#L1

This dependency isn't bundled with the component, because it isn't part of the source code. However, it is necessary for some browsers like IE11. I can't recall getting that exception with older versions of Vue. I'll try to fix it, by getting rid of `babel-polyfill` all together.

**Comment by Sun0fABeach** [comment]
Chrome (or any other browser) doesn't see the async/await syntax, because your bundle already transpiled it to regeneratorRuntime calls. If you take a look at your export `dist/index.js`, you will find no async/await, but regeneratorRuntime instead. This is what the browser can't handle because you did not provide that runtime as a polyfill. Check out this article, it perfectly adresses your problem:
https://bagja.net/blog/regenerator-runtime-is-not-defined.html

BTW: After importing babel-polyfill and looking at `model` in devtools, it is no longer empty and gets updated on resize. My guess is that in my actual project, there seems to be a conflict with another library. I will investigate that tomorrow.

**Comment by adi518** [comment]
Sure, let me know so we can get to the bottom of it. 👍 

As for the transpiled code, I think I already have a good clue of what's causing it.

**Comment by Sun0fABeach** [comment]
After commenting out all other libs in my project, the model unfortunately is still not reactive and I'm running out of ideas. If you like to get your hands dirty and reproduce the issue for you, you can clone this repo and try installing your lib. You'll only need to run the frontend part.
https://github.com/Sun0fABeach/weather-service
Sorry, that's all I can do for now. Thanks for the support, though!

**Comment by adi518** [comment]
Updated my demo app to latest `vue-cli` boilerplate and still can't reproduce this issue, but if it persists please reopen (anyone who experiences this).
